export function auditActionLabel(action: string): string {
  const map: Record<string, string> = {
    login: "登录",
    login_failed: "登录失败",
    logout: "退出登录",
    register: "账号注册",
    password_change: "密码修改",
    drop: "退课",
    enroll_submit: "提交注册",
    registration_submit: "提交注册",
    ENROLL: "注册",
    grade_update: "成绩更新",
    GRADE_BULK_UPDATE: "批量成绩更新",
    faculty_grade_submit: "教师成绩提交",
    admin_crud: "数据管理",
    admin_action: "管理操作",
    promote_waitlist: "候补补位",
    WAITLIST_PROMOTED: "候补补位",
    AUTO_PROMOTE_WAITLIST: "自动候补补位",
    ADMIN_DROP: "强制退课",
    ADMIN_BULK_DROP: "批量退课",
    ADMIN_BULK_ENROLL: "批量注册",
    ADMIN_BULK_UPDATE_STUDENT_STATUS: "批量状态更新",
    ADMIN_SECTION_SWAP: "换班操作",
    ADMIN_UPDATE_REG_WINDOW: "注册窗口更新",
    BULK_APPROVE: "批量审批",
    BULK_STATUS_EMAIL: "批量状态邮件",
    swap: "换班",
    enroll_to_completed: "结课归档",
    advisor_assignment: "导师分配",
    advisor_advisee_view: "查看学生",
    advisor_note_create: "创建备注",
    academic_request_submit: "学术申请提交",
    academic_request_decision: "学术申请审批",
    academic_request_step_decision: "审批步骤操作",
    academic_request_step_reassigned: "审批重新分配",
    academic_request_owner_transition: "申请流转",
    faculty_roster_view: "查看名册",
    student_hold_create: "学籍限制创建",
    student_hold_resolve: "学籍限制解除",
    student_support_request: "学生支持请求",
    CREDIT_OVERLOAD_REQUEST: "超学分申请",
    NOTE_CREATED: "创建备注",
    NOTE_DELETED: "删除备注",
    PROFILE_UPDATE: "资料更新",
    ROLE_UPDATE: "角色变更",
    STUDENT_TAGS_SET: "学生标签更新",
    CALENDAR_EVENT_CREATED: "创建日历事件",
    CALENDAR_EVENT_UPDATED: "更新日历事件",
    CALENDAR_EVENT_DELETED: "删除日历事件",
    NOTIFY_SECTION: "教学班通知",
    DIGEST_SENT: "发送周报",
    SYSTEM_SETTING_UPDATE: "系统设置更新",
  };
  return map[action] ?? action;
}

export function auditEntityTypeLabel(type: string): string {
  const map: Record<string, string> = {
    auth: "认证",
    enrollment: "注册",
    Enrollment: "注册",
    student: "学生",
    student_profile: "学生档案",
    student_import: "学生导入",
    student_hold: "学籍限制",
    student_tags: "学生标签",
    course: "课程",
    course_import: "课程导入",
    section: "教学班",
    section_import: "教学班导入",
    term: "学期",
    user: "账号",
    User: "账号",
    faculty: "教师",
    advisor: "顾问",
    academic_request: "学术申请",
    academic_request_step: "审批步骤",
    CalendarEvent: "日历事件",
    system_setting: "系统设置",
    invite_code: "邀请码",
    support_request: "支持请求",
    cohort_message: "群发消息",
    DigestEmail: "周报邮件",
    StudentNote: "学生备注",
  };
  return map[type] ?? type;
}

export function auditActorDisplay(email: string | null | undefined): string {
  if (!email || email === "system" || email === "SYSTEM") return "系统";
  return email;
}
